services:
  database:
    image: postgres:17.4-alpine3.21
    container_name: postgres
    hostname: database.internal
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ./migrations/dump-app-202503030115.sql:/docker-entrypoint-initdb.d/dump-app-202503030115.sql
    ports:
      - 5432:5432
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge
