import "./global.css";

export const metadata = {
	title: "Welcome to frontend",
	description: "Generated by create-nx-workspace",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
	return (
		<html lang="en">
			<body className="w-full">
				<div className="mt-5 mx-auto max-w-screen-lg w-min">{children}</div>
			</body>
		</html>
	);
}
